### ISSUE TITLE
Clarify polling interval

### ISSUE THREAD

**Issue by subzero79** [onedr0p/telegram-sonarr-bot#5]
Couldn't find the interval in the code, must be controlled by node-telegram-bot-api i guess. I really don't know anything about node.js

Can this be added to the config.json or as env variable?

I did some shorts measures with iptables LOG when i did the telegram bot bash, and in a month the bot i estimated that it could do up to 2-3GB traffic running 24/7 with a 2 second polling if i recall correctly

**Comment by onedr0p** [comment]
Via [node-telegram-bot-api](https://github.com/yagop/node-telegram-bot-api) the polling interval is set to 2 seconds. This can be added to the config, but I will keep the interval set to 2 seconds for now. 

Instead of polling we can use webhooks which won't do any polling at all, but this requires more configuration on the person setting up the bot, like SSL cert and a domain name.

**Comment by subzero79** [comment]
Webhooks sounds more complicated and I am still trying to understand them. 
I'll Run a couple of measurements with the bot running (with no messages) for 15 minutes or so you can extrapolate the use.

**Comment by onedr0p** [comment]
Webhooks are basically endpoints to your bot, so for example you would have https://www.yourwebsite.com/yourbotname and then thru POST you would have methods that are the commands you send. For example, the POST data sent to this endpoint would be

```json
{
    'command': '/q Ren and Stimpy'
}
```

That would be then sent to your bot with the response of series to choose being set back to the conversation and it continues for each chain of commands you send. So instead of polling the server looking for a message, it would get pushed to the bot instead.

**Comment by subzero79** [comment]
About the stats:
In my bot originally i just put a rule for destination and source of api.telegram.org (according to dig that's 4 ip address) in the INPUT and OUTPUT iptables chains
Now for some reason when running the bot in docker the packets don't hit the output and input chain (i have to look into that), but you can get network stats from docker stats container_name.

In 2 hour and 48 minute period the bot consumed 20.88MB TX and 6.784MB RX, so that's 27.664MB, at rate per minute that's 168.434 KB/min.
So a day the bot consumes 236MB, a month that goes to 7GB, much more than i though. 

I've just changed the poll interval at node-telegram-bot-api to 6000, let's see if the data cut's down linearly.

**Comment by onedr0p** [comment]
Thanks for the stats. Mathematically at 6 seconds it should be cut down by 2/3rds. Do you notice any significant different when interacting with the bot?

**Comment by subzero79** [comment]
i have not yet interacted with the bot to measure the differences. But yes, should be cut down to 2/3. In this case 2.27KB/s or 136KB/min. That's about 5GB a month
So probably the webhooks are a better use, i was reading about that in the bot api.

**Comment by onedr0p** [comment]
I will have time tomorrow to work on getting webhooks to work. I don't believe it will be that hard. Maintaining 2x2 branches of code might be a bit painful so I'll see if I can instead make it a option to use one or the other.

**Comment by onedr0p** [comment]
Closing this issue, I don't bandwidth is really a major issue with polling. We could open a new issue for using a webhook but that method requires more user configuration.

**Comment by subzero79** [comment]
No problem. I was lately using webhooks in combination with kodi to toggle monitoring state in sonarr. I'll see if I can configure something.
